### ISSUE TITLE
[Design] Define user journeys

### ISSUE THREAD

**Issue by joshblack** [abbeyhrt/keep-up-old#4]

**Comment by abbeyhrt** [comment]
As a roommate, i want to know when i need to vaccuum so that i am doing my fair share.
As a home-owner, i want to know when to schedule maintenance of my house so that i keep it in good repair.(this might be a stretch but essentially the idea is knowing when to do bigger tasks like cleaning gutters or power washing the drive)
As head of the household, i want to be able to organize tasks between other occupants so that everyone knows what they need to do
As a user, i want to be able to mark each task as completed so i can keep track of what i've done.
As a parent, i want to be able to add descriptions to tasks so that my children know how to complete each task.
As a user, i can assign tasks to a room so i know where certain tasks need to be performed.
As a user, i can log in without FB, twitter, google, etc so that i can still use this if i don't have those things.
As a user, i want to assign frequency to tasks so that I am not doing a certain task too often or not often enough.
As a user, i want to be able to set alerts so that i don't forget to do certain tasks.
As a user, i want to be able to set number of bedrooms, bathrooms, etc on a house so that i can represent what i need to do.
As a user, i want to be able to name rooms so that i can communicate where what work needs to be done
